### ISSUE TITLE
Problem with encoding movie

### ISSUE THREAD

**Issue by YinHana0505** [nicholascarey/loomeR#44]
Hi Nicholas,

Thanks for creating this package. I am new to R. I am trying to use your loomeR code to create a looming stimulus for my animal behavioural experiment. I tried to copy paste your code for trying but I could not encode the movie because it said that permission denied and image files are deleted. Because I am completely new to this I do not know what is the problem. I hope that you can advise me. This is the code tat I saw:

constant_speed_model detected.
[==================================================] 100% Generating image files
Encoding movie...
ffmpeg version 2021-06-06-git-43295ae6a9-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  1.100 / 59.  1.100
  libavformat    59.  2.101 / 59.  2.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.101 /  8.  0.101
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, image2, from 'loom_img_%06d.png':
  Duration: 00:00:02.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, pal8(pc), 1280x1024 [SAR 2834:2834 DAR 5:4], 60 fps, 60 tbr, 60 tbn
animation.mp4: Permission denied
Deleting image files...

# Conversion complete # -------------------------
Resulting animation.mp4 video should be 2.00s in duration.

Any ffmpeg errors should be listed above
>

**Comment by nicholascarey** [comment]
Hi. Sorry to hear you are having trouble. It looks like a fmmpeg error, so I'm not sure i'll be able to help much. When it comes to the ffmpeg errors, I do not have much experience with them, especially you are working on a PC (all the development was done on a Mac). Are you on a Windows PC? I am not familiar with PCs at all. 

If you google "ffmpeg" and "Permission denied" you may find more help. It looks like you don't have permission to write to the  location the function is trying to use. So you can try a couple of things. 

- change the working directory in R using `setwd` to one your user account is allowed to write to, like your documents folder. 
- try it using an admin account 
- lastly, try a different computer, especially try a Mac.

Let me know how you get on.

**Comment by YinHana0505** [comment]
Hi Nicolas,

Yes I am using a Windows PC and I could not figure out what is the ffmpeg error that leads to this problem. 

I have tried setting the working directory, and I am using my personal laptop and admin account. But still facing the same problem.  I have yet to try a Mac because I dont have one.

But thank you for your advice. I will try to find out more on ffmpeg.

**Comment by nicholascarey** [comment]
For the record - was an  issue with anti virus software. Worked when this was disabled.
